# Generated by Django 4.1.1 on 2022-10-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handMade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
