# Generated by Django 4.1.1 on 2022-10-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handMade', '0003_product_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='handMade.categories'),
        ),
    ]
