# Generated by Django 4.1.1 on 2022-10-18 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('handMade', '0004_categories_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='Cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
