# Generated by Django 4.1.1 on 2022-10-18 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handMade', '0005_product_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='name',
        ),
        migrations.AddField(
            model_name='categories',
            name='title',
            field=models.ForeignKey(blank=True, db_column='Main category', null=True, on_delete=django.db.models.deletion.CASCADE, to='handMade.categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='sub_category',
            field=models.CharField(db_column='Sub category', max_length=200, null=True),
        ),
    ]
